name: CI (except main)

on:
  push:
    branches-ignore:
      - 'main'

env:
  php_version: '8.2'

jobs:
  phpcs-drupal:
    name: Drupal coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: guix77/phpcs-drupal-action@php8.3

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
      with:
        php_version: ${{ env.php_version }}
        php_extensions: gd
    - uses: php-actions/phpunit@v3
      with:
        configuration: "./phpunit.xml"
        memory_limit: "256M"
        php_extensions: xdebug
        coverage_clover: "coverage/clover.xml"
        args: --migrate-configuration
      env:
          XDEBUG_MODE: coverage
          TEST_NAME: my_deployment_phpunit
  
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@c0c6e403b6c6c44657450627093edddf3b905c5b # 2.9.0

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get Composer cache directory
        id: composer-cache-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a # v2.1.3
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # - name: Avoid GitHub rate limit for Composer
      #   run: composer config -g github-oauth.github.com ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}

      - name: Composer install
        run: composer install --no-dev --no-interaction --no-progress
